version: '3.8'

services:
  database:
    build: ./services/DB-Service
    ports:
      - "8000:8000"
    volumes:
      - ./services/DB-Service:/app

  frontend:
    build: ./app/web
    ports:
      - "3000:3000"
    depends_on:
      - database

